%% Carbon loss calcs

clear
close all


%% 
% consumption for unassim -> PIC
% repro for "dead eggs" -> ?DIC, ?DOC, & ?POC

load([fpath 'Means',var,'_Climatol_' harv '_' cfile '.mat'],'sf_mcon',...
    'sf_tmcon','sp_tmcon','sd_tmcon','mf_tmcon','mp_tmcon',...
    'md_tmcon','lp_tmcon','ld_tmcon',...
    'mf_tmrep','lp_tmrep','ld_tmrep',...
    'sf_mcon','sp_mcon','sd_mcon','mf_mcon','mp_mcon',...
    'md_mcon','lp_mcon','ld_mcon',...
    'mf_mrep','lp_mrep','ld_mrep',...
    'mf_rep','lp_rep','ld_rep',...
    'sf_con','sp_con','sd_con',...
    'mf_con','mp_con','md_con',...
    'lp_con','ld_con');

% natural mort for POC?
load([fpath 'Means_nu_gam_die_clev_Climatol_' harv '_' cfile '.mat'],...
    'sf_tmdie','sp_tmdie','sd_tmdie','mf_tmdie','mp_tmdie',...
    'md_tmdie','lp_tmdie','ld_tmdie',...
    'sf_mdie','sp_mdie','sd_mdie','mf_mdie','mp_mdie',...
    'md_mdie','lp_mdie','ld_mdie',...
    'time','lyr',...
    'sf_die','sp_die','sd_die','mf_die','mp_die','md_die',...
    'lp_die','ld_die');

% metab for DIC
