function parsave(name ,...
        Clim_Sml_f,Clim_Sml_p,Clim_Sml_d,Clim_Med_f,...
        Clim_Med_p,Clim_Med_d,Clim_Lrg_p,Clim_Lrg_d,...
        Clim_Bent)
    
    save(name,...
        'Clim_Sml_f','Clim_Sml_p','Clim_Sml_d','Clim_Med_f',...
        'Clim_Med_p','Clim_Med_d','Clim_Lrg_p','Clim_Lrg_d',...
        'Clim_Bent')
end
