clear

ncread_save_fishmip_hist_obsclim_pristine_onedeg_bio
ncread_save_fishmip_hist_ctrlclim_pristine_onedeg_bio
ncread_save_fishmip_hist_obsclim_fished_onedeg_bio
ncread_save_fishmip_hist_ctrlclim_fished_onedeg_bio