
% ncread_save_fishmip_hist_obsclim_pristine_15arcmin_bio
% ncread_save_fishmip_hist_ctrlclim_pristine_15arcmin_bio
% ncread_save_fishmip_hist_obsclim_fished_15arcmin_bio
% ncread_save_fishmip_hist_ctrlclim_fished_15arcmin_bio
% ncread_save_fishmip_pi_ctrlclim_pristine_15arcmin_bio
% ncread_save_fishmip_pi_ctrlclim_fished_15arcmin_bio
ncread_save_fishmip_spin_ctrlclim_pristine_15arcmin_bio
ncread_save_fishmip_spin_ctrlclim_fished_15arcmin_bio
