% Pippa Edwards POC flux

clear 
close all

%%
epath = '/Volumes/petrik-lab/Feisty/Obs_data/Export_stat_products/Pippa/';

ppath = '/Users/cpetrik/Petrik Lab Group Dropbox/Colleen Petrik/OCB_BGC/export_flux/Edwards/';

ncdisp([epath 'estpocbayes_poc_1500_mapped.nc'])

%%
% description = 'Statistical model outputs generated by Pippa Edwards (pe1n24@soton.ac.uk) for paper Capturing the Global Variability of Marine Particulate Organic Carbon Flux: A Hierarchical Bayesian Approach. This is a monthly climatology for all data between 1997-2022. Please read the paper for methodology.'
% Dimensions:
%            date = 298
%            lat  = 180
%            lon  = 360
% Variables:
%     meanlogpoc
%            Size:       360x180x298
%            Dimensions: lon,lat,date
%            Datatype:   double
%            Attributes:
%                        _FillValue  = NaN
meanlogpoc_units       = 'ln(mg/m2/day)';
meanlogpoc_descrip = 'Log-transformed mean poc generated from mu and sigma';
%     meanpoc   
%            Size:       360x180x298
%            Dimensions: lon,lat,date
%            Datatype:   double
%            Attributes:
%                        _FillValue  = NaN
meanpoc_units       = 'mg/m2/day';
meanpoc_descrip = 'Mean poc generated from mu and sigma then taken out of log-space';
%     depth     
%            Size:       360x180x298
%            Dimensions: lon,lat,date
%            Datatype:   double
%            Attributes:
%                        _FillValue  = NaN
depth_units       = 'm';
depth_descrip = 'Depth at which flux is calculated at';
%     lat       
%            Size:       180x1
%            Dimensions: lat
%            Datatype:   single
%            Attributes:
%                        _FillValue = NaN
%                        long_name  = 'latitude'
%                        units      = 'degrees_north'
%     lon       
%            Size:       360x1
%            Dimensions: lon
%            Datatype:   single
%            Attributes:
%                        _FillValue = NaN
%                        units      = 'degrees_east'
%                        long_name  = 'longitude'
%     date      
%            Size:       298x1
%            Dimensions: date
%            Datatype:   int64
%            Attributes:
date_units    = 'days since 1997-09-01';
date_calendar = 'proleptic_gregorian';

%% POC flux 1000 m
ncid = netcdf.open([epath 'estpocbayes_poc_1500_mapped.nc'],'NC_NOWRITE');
[ndims,nvars,ngatts,unlimdimid] = netcdf.inq(ncid);
for i = 1:nvars
    varname = netcdf.inqVar(ncid, i-1);
    eval([ varname ' = netcdf.getVar(ncid,i-1);']);
    eval([ varname '(' varname ' == 99999) = NaN;']);
end
netcdf.close(ncid);

% allBB = biomass;
% clear biomass

%% map info
[geolat,geolon] = meshgrid(lat,lon);

[ni,nj]=size(geolon);
geolon = double(geolon);
geolat = double(geolat);

plotminlat=-90; %Set these bounds for your data
plotmaxlat=90;
plotminlon=-280;
plotmaxlon=80;
latlim=[plotminlat plotmaxlat];
lonlim=[plotminlon plotmaxlon];

load coastlines;  

%% maps

test = squeeze(meanlogpoc(:,:,1));

figure; pcolor(geolat); shading flat; colorbar
figure; pcolor(geolon); shading flat; colorbar
figure; pcolor(test); shading flat; colorbar

%%
close all


%% mean over whole time
mpoc = mean(meanlogpoc,3,'omitnan');
yr=(double(date)/365)+1997+(9/12);

figure(2)
axesm ('Robinson','MapLatLimit',latlim,'MapLonLimit',lonlim,'frame','on',...
    'Grid','off','FLineWidth',1,'origin',[0 -100 0])
surfm(geolat,geolon,mpoc)
cmocean('matter')
h=patchm(coastlat+0.5,coastlon+0.5,'w','FaceColor',[0.75 0.75 0.75]);
clim([2 5]);
hcb = colorbar('h');
title('log10 mean POC flux at 1500 m (mg/m2/day) 1997-2022')
stamp('')
print('-dpng',[ppath 'meanlogpoc_1500m_mean.png'])

%% save
save([epath 'estpocbayes_poc_1500_mapped.mat'],'date','date_units','date_calendar','yr',...
    'depth','depth_descrip','meanlogpoc','meanlogpoc_descrip','meanlogpoc_units',...
    'meanpoc','meanpoc_descrip','meanpoc_units')