sizespec_netcdf_save_gfdl_pi_hist_pristine;
sizespec_netcdf_save_gfdl_pi_fut_pristine;
sizespec_netcdf_save_gfdl_hist_pristine;
sizespec_netcdf_save_gfdl_ssp126_pristine;
sizespec_netcdf_save_gfdl_ssp585_pristine;

sizespec_netcdf_save_ipsl_pi_hist_pristine;
sizespec_netcdf_save_ipsl_pi_fut_pristine;
sizespec_netcdf_save_ipsl_hist_pristine;
sizespec_netcdf_save_ipsl_ssp126_pristine;
sizespec_netcdf_save_ipsl_ssp585_pristine;